class CountryCodes
  def self.all_country_codes
    codes = []
    codes << ['Andorra', 'AD']
    codes << ['United Arab Emirates', 'AE']
    codes << ['Afghanistan', 'AF']
    codes << ['Antigua and Barbuda', 'AG']
    codes << ['Anguilla', 'AI']
    codes << ['Albania', 'AL']
    codes << ['Armenia', 'AM']
    codes << ['Angola', 'AO']
    codes << ['Antarctica', 'AQ']
    codes << ['Argentina', 'AR']
    codes << ['American Samoa', 'AS']
    codes << ['Austria', 'AT']
    codes << ['Australia', 'AU']
    codes << ['Aruba', 'AW']
    codes << ['Åland Islands', 'AX']
    codes << ['Azerbaijan', 'AZ']
    codes << ['Bosnia and Herzegovina', 'BA']
    codes << ['Barbados', 'BB']
    codes << ['Bangladesh', 'BD']
    codes << ['Belgium', 'BE']
    codes << ['Burkina Faso', 'BF']
    codes << ['Bulgaria', 'BG']
    codes << ['Bahrain', 'BH']
    codes << ['Burundi', 'BI']
    codes << ['Benin', 'BJ']
    codes << ['Saint Barthélemy', 'BL']
    codes << ['Bermuda', 'BM']
    codes << ['Brunei Darussalam', 'BN']
    codes << ['Bolivia, Plurinational State of', 'BO']
    codes << ['Bonaire, Sint Eustatius and Saba', 'BQ']
    codes << ['Brazil', 'BR']
    codes << ['Bahamas', 'BS']
    codes << ['Bhutan', 'BT']
    codes << ['Bouvet Island', 'BV']
    codes << ['Botswana', 'BW']
    codes << ['Belarus', 'BY']
    codes << ['Belize', 'BZ']
    codes << ['Canada', 'CA']
    codes << ['Cocos (Keeling) Islands', 'CC']
    codes << ['Congo, the Democratic Republic of the', 'CD']
    codes << ['Central African Republic', 'CF']
    codes << ['Congo', 'CG']
    codes << ['Switzerland', 'CH']
    codes << ['Côte d\'Ivoire', 'CI']
    codes << ['Cook Islands', 'CK']
    codes << ['Chile', 'CL']
    codes << ['Cameroon', 'CM']
    codes << ['China', 'CN']
    codes << ['Colombia', 'CO']
    codes << ['Costa Rica', 'CR']
    codes << ['Cuba', 'CU']
    codes << ['Cabo Verde', 'CV']
    codes << ['Curaçao', 'CW']
    codes << ['Christmas Island', 'CX']
    codes << ['Cyprus', 'CY']
    codes << ['Czech Republic', 'CZ']
    codes << ['Germany', 'DE']
    codes << ['Djibouti', 'DJ']
    codes << ['Denmark', 'DK']
    codes << ['Dominica', 'DM']
    codes << ['Dominican Republic', 'DO']
    codes << ['Algeria', 'DZ']
    codes << ['Ecuador', 'EC']
    codes << ['Estonia', 'EE']
    codes << ['Egypt', 'EG']
    codes << ['Western Sahara', 'EH']
    codes << ['Eritrea', 'ER']
    codes << ['Spain', 'ES']
    codes << ['Ethiopia', 'ET']
    codes << ['Finland', 'FI']
    codes << ['Fiji', 'FJ']
    codes << ['Falkland Islands (Malvinas)', 'FK']
    codes << ['Micronesia, Federated States of', 'FM']
    codes << ['Faroe Islands', 'FO']
    codes << ['France', 'FR']
    codes << ['Gabon', 'GA']
    codes << ['United Kingdom of Great Britain and Northern Ireland', 'GB']
    codes << ['Grenada', 'GD']
    codes << ['Georgia', 'GE']
    codes << ['French Guiana', 'GF']
    codes << ['Guernsey', 'GG']
    codes << ['Ghana', 'GH']
    codes << ['Gibraltar', 'GI']
    codes << ['Greenland', 'GL']
    codes << ['Gambia', 'GM']
    codes << ['Guinea', 'GN']
    codes << ['Guadeloupe', 'GP']
    codes << ['Equatorial Guinea', 'GQ']
    codes << ['Greece', 'GR']
    codes << ['South Georgia and the South Sandwich Islands', 'GS']
    codes << ['Guatemala', 'GT']
    codes << ['Guam', 'GU']
    codes << ['Guinea-Bissau', 'GW']
    codes << ['Guyana', 'GY']
    codes << ['Hong Kong', 'HK']
    codes << ['Heard Island and McDonald Islands', 'HM']
    codes << ['Honduras', 'HN']
    codes << ['Croatia', 'HR']
    codes << ['Haiti', 'HT']
    codes << ['Hungary', 'HU']
    codes << ['Indonesia', 'ID']
    codes << ['Ireland', 'IE']
    codes << ['Israel', 'IL']
    codes << ['Isle of Man', 'IM']
    codes << ['India', 'IN']
    codes << ['British Indian Ocean Territory', 'IO']
    codes << ['Iraq', 'IQ']
    codes << ['Iran, Islamic Republic of', 'IR']
    codes << ['Iceland', 'IS']
    codes << ['Italy', 'IT']
    codes << ['Jersey', 'JE']
    codes << ['Jamaica', 'JM']
    codes << ['Jordan', 'JO']
    codes << ['Japan', 'JP']
    codes << ['Kenya', 'KE']
    codes << ['Kyrgyzstan', 'KG']
    codes << ['Cambodia', 'KH']
    codes << ['Kiribati', 'KI']
    codes << ['Comoros', 'KM']
    codes << ['Saint Kitts and Nevis', 'KN']
    codes << ['Korea, Democratic People\'s Republic of', 'KP']
    codes << ['Korea, Republic of', 'KR']
    codes << ['Kuwait', 'KW']
    codes << ['Cayman Islands', 'KY']
    codes << ['Kazakhstan', 'KZ']
    codes << ['Lao People\'s Democratic Republic', 'LA']
    codes << ['Lebanon', 'LB']
    codes << ['Saint Lucia', 'LC']
    codes << ['Liechtenstein', 'LI']
    codes << ['Sri Lanka', 'LK']
    codes << ['Liberia', 'LR']
    codes << ['Lesotho', 'LS']
    codes << ['Lithuania', 'LT']
    codes << ['Luxembourg', 'LU']
    codes << ['Latvia', 'LV']
    codes << ['Libya', 'LY']
    codes << ['Morocco', 'MA']
    codes << ['Monaco', 'MC']
    codes << ['Moldova, Republic of', 'MD']
    codes << ['Montenegro', 'ME']
    codes << ['Saint Martin (French part)', 'MF']
    codes << ['Madagascar', 'MG']
    codes << ['Marshall Islands', 'MH']
    codes << ['Macedonia, the former Yugoslav Republic of', 'MK']
    codes << ['Mali', 'ML']
    codes << ['Myanmar', 'MM']
    codes << ['Mongolia', 'MN']
    codes << ['Macao', 'MO']
    codes << ['Northern Mariana Islands', 'MP']
    codes << ['Martinique', 'MQ']
    codes << ['Mauritania', 'MR']
    codes << ['Montserrat', 'MS']
    codes << ['Malta', 'MT']
    codes << ['Mauritius', 'MU']
    codes << ['Maldives', 'MV']
    codes << ['Malawi', 'MW']
    codes << ['Mexico', 'MX']
    codes << ['Malaysia', 'MY']
    codes << ['Mozambique', 'MZ']
    codes << ['Namibia ', 'NA']
    codes << ['New Caledonia', 'NC']
    codes << ['Niger', 'NE']
    codes << ['Norfolk Island', 'NF']
    codes << ['Nigeria', 'NG']
    codes << ['Nicaragua', 'NI']
    codes << ['Netherlands', 'NL']
    codes << ['Norway', 'NO']
    codes << ['Nepal', 'NP']
    codes << ['Nauru', 'NR']
    codes << ['Niue', 'NU']
    codes << ['New Zealand', 'NZ']
    codes << ['Oman', 'OM']
    codes << ['Panama', 'PA']
    codes << ['Peru', 'PE']
    codes << ['French Polynesia', 'PF']
    codes << ['Papua New Guinea', 'PG']
    codes << ['Philippines', 'PH']
    codes << ['Pakistan', 'PK']
    codes << ['Poland', 'PL']
    codes << ['Saint Pierre and Miquelon', 'PM']
    codes << ['Pitcairn', 'PN']
    codes << ['Puerto Rico', 'PR']
    codes << ['Palestine, State of', 'PS']
    codes << ['Portugal', 'PT']
    codes << ['Palau', 'PW']
    codes << ['Paraguay', 'PY']
    codes << ['Qatar', 'QA']
    codes << ['Réunion', 'RE']
    codes << ['Romania', 'RO']
    codes << ['Serbia', 'RS']
    codes << ['Russian Federation', 'RU']
    codes << ['Rwanda', 'RW']
    codes << ['Saudi Arabia', 'SA']
    codes << ['Solomon Islands', 'SB']
    codes << ['Seychelles', 'SC']
    codes << ['Sudan', 'SD']
    codes << ['Sweden', 'SE']
    codes << ['Singapore', 'SG']
    codes << ['Saint Helena, Ascension and Tristan da Cunha', 'SH']
    codes << ['Slovenia', 'SI']
    codes << ['Svalbard and Jan Mayen', 'SJ']
    codes << ['Slovakia', 'SK']
    codes << ['Sierra Leone', 'SL']
    codes << ['San Marino', 'SM']
    codes << ['Senegal', 'SN']
    codes << ['Somalia', 'SO']
    codes << ['Suriname', 'SR']
    codes << ['South Sudan', 'SS']
    codes << ['Sao Tome and Principe', 'ST']
    codes << ['El Salvador', 'SV']
    codes << ['Sint Maarten (Dutch part)', 'SX']
    codes << ['Syrian Arab Republic', 'SY']
    codes << ['Swaziland', 'SZ']
    codes << ['Turks and Caicos Islands', 'TC']
    codes << ['Chad', 'TD']
    codes << ['French Southern Territories', 'TF']
    codes << ['Togo', 'TG']
    codes << ['Thailand', 'TH']
    codes << ['Tajikistan', 'TJ']
    codes << ['Tokelau', 'TK']
    codes << ['Timor-Leste', 'TL']
    codes << ['Turkmenistan', 'TM']
    codes << ['Tunisia', 'TN']
    codes << ['Tonga', 'TO']
    codes << ['Turkey', 'TR']
    codes << ['Trinidad and Tobago', 'TT']
    codes << ['Tuvalu', 'TV']
    codes << ['Taiwan, Province of China', 'TW']
    codes << ['Tanzania, United Republic of', 'TZ']
    codes << ['Ukraine', 'UA']
    codes << ['Uganda', 'UG']
    codes << ['United States Minor Outlying Islands', 'UM']
    codes << ['United States of America', 'US']
    codes << ['Uruguay', 'UY']
    codes << ['Uzbekistan', 'UZ']
    codes << ['Holy See', 'VA']
    codes << ['Saint Vincent and the Grenadines', 'VC']
    codes << ['Venezuela, Bolivarian Republic of', 'VE']
    codes << ['Virgin Islands, British', 'VG']
    codes << ['Virgin Islands, U.S.', 'VI']
    codes << ['Viet Nam', 'VN']
    codes << ['Vanuatu', 'VU']
    codes << ['Wallis and Futuna', 'WF']
    codes << ['Samoa', 'WS']
    codes << ['Yemen', 'YE']
    codes << ['Mayotte', 'YT']
    codes << ['South Africa', 'ZA']
    codes << ['Zambia', 'ZM']
    codes << ['Zimbabwe', 'ZW']
    codes
  end
end
